[package]
name = "runtime"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]

[dependencies]
libc = { version = "0.2.17", default-features = false }

[lib]
name = "runtime"
crate-type = ["staticlib"]
